### PR TITLE
Update JetBrains getting started with tested on Rider

### PR DESCRIPTION
**Pull request by jamesmcroft**
Just thought I'd add the note in here that this appears to be supported in Rider also.

I've been doing some testing with it since the release and haven't come across any major issues. 

Think there might have been some confusion online that it is only supported by the 2 tested IDEs in this doc.

### CODE REVIEW

**Comment by p4nu** [comment]
The cycling through alternative solutions without opening the Solutions tab is unfortunately not yet working for C# in Rider

**Comment by jamesmcroft** [comment]
@p4nu do you mean having the explorer in the available windows? I seem to be able to explore alternative solutions without the explorer being open/expanded.

**Comment by jamesmcroft** [comment]
@p4nu re-testing this, this appears to have been resolved with Rider now

**Comment by Aseem-studio12** [comment]
Ok

**Pull request closed without merging**
